void loopdir() {
   // example of script to loop on all the objects of a ROOT file directory
   // and print on Postscript all TH1 derived objects
   // This script uses the file generated by tutorial hsimple.C
   //Author: Rene Brun

   TFile *f1 = TFile::Open("root://eoscms.cern.ch//store/group/phys_smp/Multijet/13TeV/MC/ZeroField/Pythia8-CUETM1-Flat-HighStatistics-MagnetOff.root");
   TIter next(f1->GetListOfKeys());
   TKey *key;
   TCanvas c1;
   while ((key = (TKey*)next())) {
   
      TClass *cl = gROOT->GetClass(key->GetClassName());
      if (!cl->InheritsFrom("TDirectory")) {
         continue;
      }

      TDirectory *dir = (TDirectory*)key->ReadObj();
      std::cout << dir->GetName() << std::endl;
   }
   c1.Print("hsimple.ps]");
}
